import fs from 'node:fs';

const path = 'index.html';
let s = fs.readFileSync(path, 'utf8');
const must = (oldText, newText, count = 1) => {
  const hits = s.split(oldText).length - 1;
  if (hits !== count) throw new Error(`Expected ${count} occurrence(s), found ${hits}: ${oldText.slice(0,80)}`);
  s = s.split(oldText).join(newText);
};

must('<html lang="en">','<html lang="en" class="js">');
must('--ease:cubic-bezier(.2,0,0,1);--easeout:cubic-bezier(.22,1,.36,1)', '--ease:cubic-bezier(.2,0,0,1);--easeout:cubic-bezier(.22,1,.36,1);--ease-standard:cubic-bezier(.4,0,.2,1);--ease-hover:cubic-bezier(.25,.1,.25,1);--spring-36:linear(0,.0791,.2369,.4041,.5522,.6723,.7649,.8339,.884,.9198,.945,.9625,.9746,.9829,.9885,.9923,.9949,.9966,.9977,.9985,.999,1,1);--dur-hover:.2s;--dur-press:.12s;--dur-reveal:.3s;--dur-cta:.36s;--ease-cta:cubic-bezier(.23,1,.32,1)');

must('.nav-mark{background:var(--blue);width:6px;height:6px;transition:transform .4s ease;pointer-events:none;position:absolute;top:0;left:-16px}', '.nav-mark{background:var(--blue);width:6px;height:6px;transform:translateY(var(--mark-y,8px)) rotate(var(--mark-r,0deg));transition:transform .4s var(--ease-standard),opacity var(--dur-hover) var(--ease-hover);pointer-events:none;position:absolute;top:0;left:-16px}.nav-mark.is-off{opacity:0}');

must('.btn{height:44px;font-family:var(--mono);letter-spacing:.06em;text-transform:uppercase;white-space:nowrap;align-items:center;font-size:12px;font-weight:500;line-height:1;text-decoration:none;display:inline-flex;position:relative}', '.btn{height:44px;font-family:var(--mono);letter-spacing:.06em;text-transform:uppercase;white-space:nowrap;align-items:center;font-size:12px;font-weight:500;line-height:1;text-decoration:none;display:inline-flex;position:relative;transition:transform var(--dur-press) var(--ease-cta)}.btn:active{transform:scale(.985)}');

must('.btn-primary{background:var(--blue);border:1px solid var(--blue);min-width:208px;color:var(--warmwhite);gap:12px;padding:2px 11px 2px 2px}.btn-primary .tile{width:38px;height:38px;background:white;color:var(--blue);display:grid;place-items:center}', '.btn-primary{background:var(--blue);border:1px solid var(--blue);min-width:208px;color:var(--warmwhite);gap:12px;padding:2px 11px 2px 2px;overflow:hidden}.btn-primary:before{content:"";clip-path:inset(2px calc(100% - 40px) 2px 2px);transition:clip-path var(--dur-cta) var(--ease-cta);background:#fff;position:absolute;inset:0}.btn-slot{flex:none;width:38px;height:38px}.btn-rail{pointer-events:none;width:calc(100% - 42px);height:38px;transition:translate var(--dur-cta) var(--ease-cta);position:absolute;top:2px;left:2px}.btn-tile{z-index:1;width:38px;height:38px;color:var(--blue);transition:rotate var(--dur-cta) var(--ease-cta);justify-content:center;align-items:center;display:flex;position:relative;rotate:0deg}.btn-label{z-index:1;text-align:center;transition:color .25s ease,translate var(--dur-cta) var(--ease-cta);position:relative}.btn-primary:hover:before,.btn-primary:focus-visible:before{clip-path:inset(2px)}.btn-primary:hover .btn-rail,.btn-primary:focus-visible .btn-rail{translate:100%}.btn-primary:hover .btn-tile,.btn-primary:focus-visible .btn-tile{rotate:360deg}.btn-primary:hover .btn-label,.btn-primary:focus-visible .btn-label{color:var(--blue);translate:-41px}');

must('.btn-secondary{background:#0562ef12;color:var(--ink);justify-content:center;gap:12px;padding:1px 12px;border:1px solid #0b101514;min-width:154px}', '.btn-secondary{background:#0562ef12;color:var(--ink);justify-content:center;gap:12px;padding:1px 12px;border:1px solid #0b101514;min-width:154px;transition:background-color var(--dur-hover) var(--ease-hover)}.btn-secondary:hover,.btn-secondary:focus-visible{background:#0562ef1c}.btn-arrow{transition:translate var(--dur-hover) var(--ease-hover);display:inline-block}.btn-secondary:hover .btn-arrow,.btn-secondary:focus-visible .btn-arrow{translate:2px -2px}');

must('.more{letter-spacing:-.006em;color:var(--ink);align-items:center;font-size:15px;font-weight:500;line-height:1.4;text-decoration:none;display:inline-flex;margin-top:36px}.more:hover{color:var(--blue)}', '.more{letter-spacing:-.006em;color:var(--ink);align-items:center;font-size:15px;font-weight:500;line-height:1.4;text-decoration:none;display:inline-flex;margin-top:36px;transition:color var(--dur-hover) var(--ease-hover)}.more:hover,.more:focus-visible{color:var(--blue)}');

must('.entry{color:var(--ink);align-items:center;gap:12px;padding:10px 12px;font-size:14px;line-height:20px;text-decoration:none;display:flex}.entry:hover{background:#fff}', '.entry{color:var(--ink);align-items:center;gap:12px;padding:10px 12px;font-size:14px;line-height:20px;text-decoration:none;display:flex;transition:background-color var(--dur-hover) var(--ease-hover)}.entry:hover,.entry:focus-visible{background:#fff}');

must('.cta .btn-primary{color:var(--blue);background:#fff;border-color:#ffffff20}.cta .btn-primary .tile{background:var(--blue);color:white}', '.cta .btn-primary{color:var(--blue);background:#fff;border-color:#ffffff20}.cta .btn-primary:before{background:var(--blue)}.cta .btn-primary .btn-tile{color:var(--warmwhite)}.cta .btn-primary:hover .btn-label,.cta .btn-primary:focus-visible .btn-label{color:var(--warmwhite)}');

const motion = `\n/* Motion: normalized to the reference system. */\nhtml.js [data-reveal]{opacity:0;translate:0 10px;transition:opacity var(--dur-reveal) var(--ease-standard),translate var(--dur-reveal) var(--ease-standard);transition-delay:var(--d,0s)}\nhtml.js [data-reveal].is-visible{opacity:1;translate:0}\nhtml.js .rail[data-reveal]{translate:0;transition-duration:.4s}\nhtml.js .rail[data-reveal] .nav a{opacity:0;translate:0 10px;transition:color var(--dur-hover) var(--ease-hover) 0s,opacity .4s var(--ease-standard) calc(.12s + var(--k,0) * 80ms),translate .4s var(--ease-standard) calc(.12s + var(--k,0) * 80ms)}\nhtml.js .rail[data-reveal].is-visible .nav a{opacity:1;translate:0}\n.note-cta,.format-switch a,.promptbar .open{transition:color var(--dur-hover) var(--ease-hover),background-color var(--dur-hover) var(--ease-hover),border-color var(--dur-hover) var(--ease-hover)}\n.note:hover .note-cta,.note:focus-visible .note-cta{background:#fff;border-color:#c9c9c9}\n.promptbar .open{cursor:pointer}.promptbar .open:hover{color:var(--ink);background:#ededf0}\n.row-icon,.plug,.place-plate,.mini{transition:border-color var(--dur-hover) var(--ease-hover),background-color var(--dur-hover) var(--ease-hover)}\n.row:hover .row-icon,.place:hover .place-plate{border-color:#c6c6c6}\n@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;transition-delay:0ms!important}.nav-mark{transition:none!important}html.js [data-reveal]{opacity:1!important;translate:0!important}.btn-primary:before{clip-path:inset(2px calc(100% - 40px) 2px 2px)!important}.btn-primary:hover .btn-rail,.btn-primary:focus-visible .btn-rail{translate:0!important}.btn-primary:hover .btn-tile,.btn-primary:focus-visible .btn-tile{rotate:0deg!important}.btn-primary:hover .btn-label,.btn-primary:focus-visible .btn-label{translate:0!important;color:inherit!important}}\n`;
const media = '@media(width<=1000px)';
if (!s.includes(media)) throw new Error('Responsive breakpoint not found');
s = s.replace(media, motion + media);

must('<aside class="rail" aria-label="Site">','<aside class="rail" aria-label="Site" data-reveal="load" style="--d:0ms">');
must('<a class="note" href="https://github.com/sushxnthd/supakeep">','<a class="note" href="https://github.com/sushxnthd/supakeep" data-reveal="load" style="--d:40ms">');
must('<h1 class="statement">','<h1 class="statement" data-reveal="load" style="--d:120ms">');
must('<p class="dek">','<p class="dek" data-reveal="load" style="--d:200ms">');
must('<div class="ways"><div class="actions">','<div class="ways"><div class="actions" data-reveal="load" style="--d:260ms">');
must('<div class="promptbar">','<div class="promptbar" data-reveal="load" style="--d:280ms">');
must('<div class="plugs">','<div class="plugs" data-reveal="load" style="--d:320ms">');
must('<figure class="figure">','<figure class="figure" data-reveal="load" style="--d:340ms">');
must('<article class="memo" id="memo">','<article class="memo" id="memo" data-reveal>');
must('<section class="section" id="what"><h2>What we do</h2><dl class="rows">','<section class="section" id="what"><h2 data-reveal style="--d:0ms">What we do</h2><dl class="rows">');
must('<div class="row"><span class="row-icon">01</span>','<div class="row" data-reveal style="--d:60ms"><span class="row-icon">01</span>');
must('<div class="row"><span class="row-icon">02</span>','<div class="row" data-reveal style="--d:120ms"><span class="row-icon">02</span>');
must('<div class="row"><span class="row-icon">03</span>','<div class="row" data-reveal style="--d:180ms"><span class="row-icon">03</span>');
must('<a class="more" href="https://github.com/sushxnthd/supakeep/blob/main/ARCHITECTURE.md">Read the architecture ↗</a>','<a class="more" data-reveal style="--d:240ms" href="https://github.com/sushxnthd/supakeep/blob/main/ARCHITECTURE.md">Read the architecture ↗</a>');
for (const id of ['production','security','writing','careers']) must(`<section class="section" id="${id}">`,`<section class="section" id="${id}" data-reveal>`);
must('<aside class="cta">','<aside class="cta" data-reveal>');
must('<footer class="foot">','<footer class="foot" data-reveal>');
must('<span class="tile">S</span><span>Build with Supakeep</span>','<span class="btn-slot" aria-hidden="true"></span><span class="btn-rail" aria-hidden="true"><span class="btn-tile">S</span></span><span class="btn-label">Build with Supakeep</span>',2);
must('<a class="btn btn-secondary" href="#what">Explore the system</a>','<a class="btn btn-secondary" href="#what">Explore the system <span class="btn-arrow" aria-hidden="true">↗</span></a>');

const oldScript = `<script>\nconst links=[...document.querySelectorAll('[data-section]')],mark=document.querySelector('.nav-mark');\nconst sections=links.map(a=>document.getElementById(a.dataset.section)).filter(Boolean);\nfunction sync(){let active=0;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<innerHeight*.35)active=i});links.forEach((a,i)=>a.toggleAttribute('aria-current',i===active));if(mark)mark.style.transform=\`translateY(\${active*29}px) rotate(\${active*90}deg)\`}\naddEventListener('scroll',sync,{passive:true});sync();\n</script>`;
const newScript = `<script>\nconst reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;\nconst revealNodes=[...document.querySelectorAll('[data-reveal]')];\nrequestAnimationFrame(()=>{document.querySelectorAll('[data-reveal="load"]').forEach(el=>el.classList.add('is-visible'))});\nif(reduceMotion){revealNodes.forEach(el=>el.classList.add('is-visible'))}else{\n  const io=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}}},{threshold:.12,rootMargin:'0px 0px -8% 0px'});\n  revealNodes.filter(el=>el.getAttribute('data-reveal')!=='load').forEach(el=>io.observe(el));\n}\nconst links=[...document.querySelectorAll('[data-section]')],mark=document.querySelector('.nav-mark');\nconst sections=links.map(a=>document.getElementById(a.dataset.section)).filter(Boolean);\nlet ticking=false;\nfunction sync(){\n  const trigger=innerHeight*.4;let active=0;\n  sections.forEach((section,i)=>{if(section.getBoundingClientRect().top<=trigger)active=i});\n  if(scrollY+innerHeight>=document.documentElement.scrollHeight-2)active=sections.length-1;\n  links.forEach((a,i)=>a.toggleAttribute('aria-current',i===active));\n  if(mark&&sections.length){\n    const current=sections[active]?.getBoundingClientRect().top??trigger;\n    const next=sections[active+1]?.getBoundingClientRect().top;\n    const progress=next==null?0:Math.min(1,Math.max(0,(trigger-current)/Math.max(next-current,1)));\n    const step=29;\n    mark.style.setProperty('--mark-y',\`${8+(active+progress)*step}px\`);\n    mark.style.setProperty('--mark-r',\`${active*90}deg\`);\n  }\n  ticking=false;\n}\naddEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(sync)}},{passive:true});\naddEventListener('resize',sync,{passive:true});sync();\n</script>`;
must(oldScript,newScript);

fs.writeFileSync(path,s);
console.log('Motion normalization applied to index.html');
