import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export const DEFAULT_POLICY={version:1,rules:[
{id:'deny-secret-export',match:{category:'secrets',action:'export_raw'},decision:'deny',reason:'Raw secrets never leave Supakeep.'},
{id:'ask-purchase',match:{category:'money',action:'purchase'},decision:'ask',reason:'Purchases require approval by default.'},
{id:'ask-send',match:{category:'communication',action:'send'},decision:'ask',reason:'External sends require approval by default.'},
{id:'ask-delete',match:{category:'destructive',action:'delete'},decision:'ask',reason:'Destructive actions require approval by default.'},
{id:'allow-read',match:{action:'read'},decision:'allow',reason:'Read-only action.'}],defaultDecision:'ask'};

export function canonicalize(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalize).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(v[k])}`).join(',')}}`}
export const sha256=s=>crypto.createHash('sha256').update(s).digest('hex');
const b64=x=>Buffer.from(x).toString('base64url'); const unb64=x=>Buffer.from(x,'base64url');

export function getOrCreateKeys(dir){fs.mkdirSync(dir,{recursive:true});const priv=path.join(dir,'grant-private.pem'),pub=path.join(dir,'grant-public.pem');if(!fs.existsSync(priv)||!fs.existsSync(pub)){const k=crypto.generateKeyPairSync('ed25519');fs.writeFileSync(priv,k.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});fs.writeFileSync(pub,k.publicKey.export({type:'spki',format:'pem'}),{mode:0o644});}return{privateKey:fs.readFileSync(priv,'utf8'),publicKey:fs.readFileSync(pub,'utf8')}}
export function getOrCreateMasterKey(dir){fs.mkdirSync(dir,{recursive:true});const p=path.join(dir,'master.key');if(!fs.existsSync(p))fs.writeFileSync(p,crypto.randomBytes(32),{mode:0o600});return fs.readFileSync(p)}
export function encryptJson(v,key){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv),ct=Buffer.concat([c.update(Buffer.from(JSON.stringify(v))),c.final()]);return{v:1,iv:iv.toString('base64url'),tag:c.getAuthTag().toString('base64url'),ciphertext:ct.toString('base64url')}}
export function decryptJson(v,key){const d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(v.iv,'base64url'));d.setAuthTag(Buffer.from(v.tag,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(v.ciphertext,'base64url')),d.final()]).toString())}

export function issueGrant(input,privateKey,now=Date.now()){const ttl=Math.max(1000,Math.min(Number(input.ttlMs??900000),86400000));const grant={v:1,id:input.id??crypto.randomUUID(),subject:input.subject??'local-user',agent:String(input.agent||'unknown-agent'),purpose:String(input.purpose||'unspecified'),actions:[...new Set(input.actions??[])].sort(),resources:[...new Set(input.resources??[])].sort(),constraints:{maxAmount:input.constraints?.maxAmount??null,currency:input.constraints?.currency??null,merchants:[...new Set(input.constraints?.merchants??[])].sort(),recipients:[...new Set(input.constraints?.recipients??[])].sort()},issuedAt:now,expiresAt:now+ttl,maxUses:Math.max(1,Number(input.maxUses??1))};const payload=b64(canonicalize(grant)),sig=crypto.sign(null,Buffer.from(payload),privateKey).toString('base64url');return{grant,token:`${payload}.${sig}`}}
export function verifyGrantToken(token,publicKey,now=Date.now()){const p=String(token||'').split('.');if(p.length!==2)throw Error('Malformed grant token');if(!crypto.verify(null,Buffer.from(p[0]),publicKey,unb64(p[1])))throw Error('Invalid grant signature');const g=JSON.parse(unb64(p[0]).toString());if(g.v!==1)throw Error('Unsupported grant version');if(now>=g.expiresAt)throw Error('Grant expired');return g}
const scope=(list,v)=>list.includes('*')||list.includes(v);
export function assertGrantAllows(g,r,useCount=0){if(g.agent!==r.agent)throw Error('Grant is bound to another agent');if(g.purpose!==r.purpose)throw Error('Grant is bound to another purpose');if(!scope(g.actions,r.action))throw Error('Action is outside grant scope');if(!scope(g.resources,r.resource))throw Error('Resource is outside grant scope');if(useCount>=g.maxUses)throw Error('Grant use limit exceeded');const c=g.constraints??{};if(r.amount!=null&&c.maxAmount!=null&&Number(r.amount)>Number(c.maxAmount))throw Error('Amount exceeds grant limit');if(r.currency&&c.currency&&r.currency!==c.currency)throw Error('Currency is outside grant scope');if(r.merchant&&c.merchants?.length&&!c.merchants.includes(r.merchant))throw Error('Merchant is outside grant scope');if(r.recipient&&c.recipients?.length&&!c.recipients.includes(r.recipient))throw Error('Recipient is outside grant scope');return true}

const DETECTORS=[['openai_api_key',/\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/g],['github_token',/\b(?:ghp|github_pat)_[A-Za-z0-9_]{20,}\b/g],['aws_access_key',/\bAKIA[0-9A-Z]{16}\b/g],['private_key',/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g],['bearer_token',/\bBearer\s+[A-Za-z0-9._~+/=-]{20,}\b/gi],['email',/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi]];
export function detectSensitive(text){const hits=[];for(const[type,re]of DETECTORS){re.lastIndex=0;let m;while((m=re.exec(text))!==null)hits.push({type,value:m[0],start:m.index,end:m.index+m[0].length})}return hits.sort((a,b)=>a.start-b.start||b.end-a.end)}
export function redactSensitive(text){const hits=detectSensitive(text),chosen=[],used=[];for(const h of hits){if(used.some(([s,e])=>h.start<e&&h.end>s))continue;used.push([h.start,h.end]);chosen.push({...h,id:crypto.randomUUID()})}let out=text;for(const s of chosen.sort((a,b)=>b.start-a.start))out=out.slice(0,s.start)+`{{SUPAKEEP:${s.type}:${s.id}}}`+out.slice(s.end);return{text:out,secrets:chosen.map(({start,end,...x})=>x)}}

function matches(m={},r={}){return Object.entries(m).every(([k,e])=>e==='*'||r[k]===e||(Array.isArray(e)&&e.includes(r[k])))}
export function evaluatePolicy(policy,r){for(const rule of policy.rules??[])if(matches(rule.match,r))return{decision:rule.decision,ruleId:rule.id,reason:rule.reason??null};return{decision:policy.defaultDecision??'ask',ruleId:null,reason:'No specific policy matched.'}}
export function riskForRequest(r){if(r.category==='secrets')return'critical';if(r.category==='money'||r.category==='destructive')return'high';if(r.action==='send'||r.action==='write')return'medium';return'low'}

export const requestHash=r=>sha256(canonicalize(r));
export function createApproval(r,ttlMs=300000){return{id:crypto.randomUUID(),requestHash:requestHash(r),createdAt:Date.now(),expiresAt:Date.now()+ttlMs,consumedAt:null}}
export function consumeApproval(a,r){if(!a)throw Error('Approval not found');if(a.consumedAt)throw Error('Approval already used');if(Date.now()>=a.expiresAt)throw Error('Approval expired');if(a.requestHash!==requestHash(r))throw Error('Approval does not match this exact action');a.consumedAt=Date.now();return true}
export function createReceipt({previousHash=null,request,decision,grantId=null,result=null}){const x={v:1,id:crypto.randomUUID(),at:Date.now(),previousHash,grantId,request,decision,result};x.hash=sha256(canonicalize(x));return x}
export function verifyReceiptChain(list){let prev=null;for(const r of list){const{hash,...body}=r;if(body.previousHash!==prev||sha256(canonicalize(body))!==hash)return false;prev=hash}return true}

export class Vault{constructor(dir,key){this.file=path.join(dir,'vault.json');this.key=key;this.items=this.load()}load(){if(!fs.existsSync(this.file))return[];return decryptJson(JSON.parse(fs.readFileSync(this.file,'utf8')),this.key)}save(){fs.writeFileSync(this.file,JSON.stringify(encryptJson(this.items,this.key),null,2),{mode:0o600})}list(){return this.items.map(({value,...x})=>x)}put({label,type='secret',value,tags=[]}){const x={id:crypto.randomUUID(),label,type,value,tags,createdAt:Date.now()};this.items.push(x);this.save();const{value:_,...safe}=x;return safe}remove(id){const n=this.items.length;this.items=this.items.filter(x=>x.id!==id);if(this.items.length===n)return false;this.save();return true}}

export class Store{constructor(dir){this.dir=dir;fs.mkdirSync(dir,{recursive:true});this.grantUses=new Map();this.revokedGrants=new Set();this.pending=new Map();this.receipts=this.load('receipts.json',[]);this.policy=this.load('policy.json',DEFAULT_POLICY)}load(f,d){const p=path.join(this.dir,f);return fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):structuredClone(d)}save(f,v){fs.writeFileSync(path.join(this.dir,f),JSON.stringify(v,null,2))}addReceipt(r){this.receipts.push(r);this.save('receipts.json',this.receipts)}}
