import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import{fileURLToPath}from'node:url';import{getOrCreateKeys,getOrCreateMasterKey,Vault,Store,redactSensitive,detectSensitive,issueGrant,verifyGrantToken,assertGrantAllows,evaluatePolicy,riskForRequest,createApproval,consumeApproval,createReceipt,verifyReceiptChain}from'./core.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dataDir=path.join(root,'data');process.chdir(root);fs.mkdirSync(dataDir,{recursive:true});const{privateKey,publicKey}=getOrCreateKeys(dataDir),vault=new Vault(dataDir,getOrCreateMasterKey(dataDir)),store=new Store(dataDir),port=Number(process.env.PORT||8787);
const send=(res,s,b)=>{const x=JSON.stringify(b);res.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','content-length':Buffer.byteLength(x)});res.end(x)};async function body(req){const a=[];for await(const c of req)a.push(c);const b=Buffer.concat(a);if(b.length>1e6)throw Error('Request body too large');return b.length?JSON.parse(b.toString()):{}}
function receipt(request,decision,grantId=null,result=null){const r=createReceipt({previousHash:store.receipts.at(-1)?.hash??null,request,decision,grantId,result});store.addReceipt(r);return r}
async function api(req,res,u){
if(req.method==='GET'&&u.pathname==='/api/status')return send(res,200,{product:'Supakeep',version:'0.1.0',vaultItems:vault.list().length,pending:[...store.pending.values()].filter(x=>x.status==='pending').length,receipts:store.receipts.length,chainValid:verifyReceiptChain(store.receipts)});
if(req.method==='GET'&&u.pathname==='/api/vault')return send(res,200,{items:vault.list()});if(req.method==='GET'&&u.pathname==='/api/pending')return send(res,200,{requests:[...store.pending.values()].filter(x=>x.status==='pending')});if(req.method==='GET'&&u.pathname==='/api/receipts')return send(res,200,{receipts:store.receipts.slice(-50).reverse(),chainValid:verifyReceiptChain(store.receipts)});
if(req.method==='POST'&&u.pathname==='/api/redact'){const b=await body(req),r=redactSensitive(String(b.text??''));return send(res,200,{redacted:r.text,detected:r.secrets.map(({value,...x})=>x),count:r.secrets.length})}
if(req.method==='POST'&&u.pathname==='/api/vault'){const b=await body(req);if(!b.label||!b.value)return send(res,400,{error:'label and value are required'});return send(res,201,{item:vault.put({label:String(b.label),type:String(b.type??'secret'),value:String(b.value)})})}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/vault/')){const ok=vault.remove(u.pathname.split('/').pop());return send(res,ok?200:404,{ok})}
if(req.method==='POST'&&u.pathname==='/api/grants'){return send(res,201,issueGrant(await body(req),privateKey))}
if(req.method==='POST'&&u.pathname==='/api/evaluate'){const b=await body(req),r=b.request??{},secretHits=detectSensitive(JSON.stringify(r));if(secretHits.some(x=>x.type!=='email'))return send(res,403,{decision:'deny',reason:'Raw secret material detected. Use a Supakeep reference.',receipt:receipt(r,'deny',null,{reason:'raw-secret'})});let g=null;if(b.grantToken){try{g=verifyGrantToken(b.grantToken,publicKey);if(store.revokedGrants.has(g.id))throw Error('Grant revoked');assertGrantAllows(g,r,store.grantUses.get(g.id)??0)}catch(e){return send(res,403,{decision:'deny',reason:e.message,receipt:receipt(r,'deny',g?.id??null,{reason:e.message})})}}const p=evaluatePolicy(store.policy,r),risk=riskForRequest(r);if(p.decision==='deny')return send(res,403,{...p,risk,receipt:receipt(r,'deny',g?.id??null,{reason:p.reason})});if(p.decision==='ask'){const id=crypto.randomUUID(),x={id,request:r,grantId:g?.id??null,grantToken:b.grantToken??null,risk,reason:p.reason,createdAt:Date.now(),status:'pending'};store.pending.set(id,x);return send(res,202,{decision:'ask',risk,pending:x})}if(g)store.grantUses.set(g.id,(store.grantUses.get(g.id)??0)+1);return send(res,200,{decision:'allow',risk,receipt:receipt(r,'allow',g?.id??null,{simulated:true})})}
const m=u.pathname.match(/^\/api\/pending\/([^/]+)\/(approve|deny)$/);if(req.method==='POST'&&m){const x=store.pending.get(m[1]);if(!x||x.status!=='pending')return send(res,404,{error:'Pending request not found'});if(m[2]==='deny'){x.status='denied';return send(res,200,{denied:true,receipt:receipt(x.request,'deny',x.grantId,{deniedByHuman:true})})}const a=createApproval(x.request);consumeApproval(a,x.request);if(x.grantToken){const g=verifyGrantToken(x.grantToken,publicKey);assertGrantAllows(g,x.request,store.grantUses.get(g.id)??0);store.grantUses.set(g.id,(store.grantUses.get(g.id)??0)+1)}x.status='approved';return send(res,200,{approved:true,receipt:receipt(x.request,'allow',x.grantId,{approvedByHuman:true,simulated:true})})}
return send(res,404,{error:'Not found'})}
function staticFile(res,u){const pub=path.join(root,'public'),p=path.resolve(pub,u.pathname==='/'?'index.html':u.pathname.slice(1));if(!p.startsWith(pub)||!fs.existsSync(p)||fs.statSync(p).isDirectory())return false;const type={'.html':'text/html; charset=utf-8'}[path.extname(p)]??'application/octet-stream';res.writeHead(200,{'content-type':type,'x-content-type-options':'nosniff'});fs.createReadStream(p).pipe(res);return true}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(u.pathname.startsWith('/api/'))return await api(req,res,u);if(staticFile(res,u))return;res.writeHead(404);res.end('Not found')}catch(e){console.error(e);send(res,500,{error:e.message||'Internal error'})}}).listen(port,'127.0.0.1',()=>console.log(`Supakeep running at http://127.0.0.1:${port}`));
